package com.ericsson.itte.mongoconnectortest;

import com.ericsson.itte.mongoconnectortest.Library;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'dyinanc' at '4/6/16 8:29 AM' with Gradle 2.10
 *
 * @author dyinanc, @date 4/6/16 8:29 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
