package com.ericsson.itte.mongoconnectortest;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dyinanc' at '4/6/16 8:29 AM' with Gradle 2.10
 *
 * @author dyinanc, @date 4/6/16 8:29 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
